[package]
name = "gitr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "env"] }
serde = { version = "1.0.202", features = ["derive"] }
serde_ini = "0.2.0"
flate2 = "1.0.30"
